name: DeepSource Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install DeepSource CLI
        run: |
          curl https://deepsource.io/cli | sh
          chmod +x ./bin/deepsource
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: ./bin/deepsource version

      - name: Report Test Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/lcov.info

      - name: List Issues Found
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: ./bin/deepsource issues list
