name: DeepSource Analysis

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Run DeepSource Analysis
        run: ./bin/deepsource report --value-file ./path/to/report
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}