name: DeepSource Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DeepSource CLI
        run: |
          curl -sSL https://deepsource.io/cli | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: deepsource --version

      - name: Run DeepSource scan
        run: deepsource scan
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
