name: DeepSource Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DeepSource CLI
        run: |
          curl -sSL https://deepsource.io/cli | sh
          mkdir -p $HOME/.local/bin
          mv deepsource $HOME/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          chmod +x $HOME/.local/bin/deepsource

      - name: Verify Installation
        run: $HOME/.local/bin/deepsource --version

      - name: Run DeepSource scan
        run: $HOME/.local/bin/deepsource scan
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
