name: Test Coverage with DeepSource

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go (or any other language you're using)
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'  # หรือ Go version ที่คุณใช้

      - name: Run tests and generate coverage
        run: |
          go test -coverprofile=coverage.out

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Upload test coverage to DeepSource
        run: |
          ./bin/deepsource report --analyzer test-coverage --key go --value-file coverage.out
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
