name: DeepSource Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Run DeepSource scan
        run: deepsource scan
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
