name: DeepSource Test Coverage Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the environment variables
      - name: Set up DEEPSOURCE_DSN
        run: echo "DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}" >> $GITHUB_ENV

      # Install the DeepSource CLI
      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      # Build the Docker image and run the tests inside the container
      - name: Build and test with Docker
        run: |
          docker build -t my-app .
          docker run --rm my-app pytest --cov=./ --cov-report xml:coverage.xml

      # Report the coverage artifact to DeepSource
      - name: Report coverage to DeepSource
        run: |
          ./bin/deepsource report --analyzer test-coverage --key docker --value-file coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
