name: DeepSource Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DeepSource Analyze
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource analyze --key ${{ secrets.DEEPSOURCE_DSN }}
