name: DeepSource Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DeepSource CLI
        run: |
          curl https://deepsource.io/cli | sh

      - name: Run DeepSource Scan
        run: |
          deepsource report --analyzer docker --key ${{ secrets.DEEPSOURCE_DSN }}
