name: DeepSource Report and Docker Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deepsource:
    runs-on: ubuntu-latest
    env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install DeepSource CLI
      run: |
        curl https://deepsource.io/cli | sh
        chmod +x ./bin/deepsource
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Verify Installation
      run: ./bin/deepsource version

    - name: Report Artifacts to DeepSource
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      run: ./bin/deepsource report --analyzer docker --value-file Dockerfile
    #   fd
