name: DeepSource Test Coverage Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the environment variables
      - name: Set up DEEPSOURCE_DSN
        run: echo "DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}" >> $GITHUB_ENV

      # Install dependencies (ไม่มีการใช้ path เพราะ package.json อยู่ใน root directory)
      - name: Install dependencies
        run: npm install

      # Install the DeepSource CLI
      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      # Run tests and generate coverage report using Jest
      - name: Run tests and generate coverage report
        run: |
          npm test --coverage --coverageReporters=cobertura

      # Report the coverage artifact to DeepSource
      - name: Report coverage to DeepSource
        run: |
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
