name: Analyze Dockerfile

on:
  push:
    branches:
      - main # ทำงานเมื่อมีการ push ไปที่สาขา main
    

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Analyze Dockerfile
        run: ./bin/deepsource analyze --analyzer docker
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
