name: DeepSource Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DeepSource CLI
        run: |
          curl -sL https://deepsource.io/cli | sh
          mv ./bin/deepsource /usr/local/bin/deepsource

      - name: Run DeepSource Scan
        run: |
          deepsource report --analyzer docker --key https://5587ef9517874bbcb55fee01f0750dc0@app.deepsource.com
