name: DeepSource Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set DeepSource DSN
        run: echo "DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}" >> $GITHUB_ENV

      - name: Install DeepSource CLI
        run: |
          curl https://deepsource.io/cli | sh
          chmod +x ./bin/deepsource
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: ./bin/deepsource version

      - name: Report Dockerfile to DeepSource
        run: ./bin/deepsource report --analyzer docker --value-file Dockerfile
